### ISSUE TITLE
fatal error: json/json.h: No such file or directory

### ISSUE THREAD

**Issue by kkkrackpot** [ethereum-mining/ethminer#265]
Hi,

I tried to compile the project on 64-bit Gentoo, without Hunter and Cuda support.

After `git clone` configuration didn't go without Hunter because of missing `BoostConfig.cmake`.
Fixed it with `git submodule update --init .` as advised here https://github.com/ethereum-mining/ethminer/issues/219#issuecomment-321755076

Then configuration went Ok:
```
/tmp/ethminer/build$ cmake .. -DHUNTER_ENABLED=OFF -DETHASHCUDA=OFF 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
------------------------------------------------------------------------
-- CMake 3.7.2
-- Build Release / Linux
------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                  ON
-- ETHASHCUDA       Build CUDA components                    OFF
-- ETHSTRATUM       Build Stratum components                 ON
------------------------------------------------------------------------

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - found
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ethminer/build
```

However, it doesn't compile:
```
[ 81%] Building CXX object libstratum/CMakeFiles/ethstratum.dir/EthStratumClient.cpp.o
In file included from /tmp/ethminer/libstratum/EthStratumClient.cpp:2:0:
/tmp/ethminer/libstratum/EthStratumClient.h:5:23: fatal error: json/json.h: No such file or directory
compilation terminated.
gmake[2]: *** [libstratum/CMakeFiles/ethstratum.dir/build.make:63: libstratum/CMakeFiles/ethstratum.dir/EthStratumClient.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:321: libstratum/CMakeFiles/ethstratum.dir/all] Error 2
gmake: *** [Makefile:150: all] Error 2
```

Found similar issue here: https://github.com/ethereum/cpp-ethereum/issues/1939
Symlinking `/usr/include/jsoncpp/json` to `/usr/include/json` does help.

But there's another issue:
```
[100%] Linking CXX executable ethminer
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ljsoncpp_lib_static
collect2: error: ld returned 1 exit status
gmake[2]: *** [ethminer/CMakeFiles/ethminer.dir/build.make:108: ethminer/ethminer] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:436: ethminer/CMakeFiles/ethminer.dir/all] Error 2
gmake: *** [Makefile:150: all] Error 2
```

At this point I got stuck...

Don't know, maybe these issues are fixed already in the master branch, or maybe it's just some Gentoo-specific problems.

The above is for your information.

Regards,
Alex

**Comment by ykhuat** [comment]
I also having all most the same issue when try to upgrade ethminer to lastested Verison:- Here my error:-
Hope some 1 can get this fix soon..
 
Scanning dependencies of target ethminer
[ 95%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
[100%] Linking CXX executable ethminer
../libethash-cuda/libethash-cuda.a(CUDAMiner.cpp.o): In function `dev::eth::CUDAMiner::configureGPU(unsigned int, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int, unsigned int)':
CUDAMiner.cpp:(.text+0x981): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x995): undefined reference to `dev::eth::Miner::s_dagCreateDevice'
../libethash-cuda/libethash-cuda.a(CUDAMiner.cpp.o): In function `dev::eth::CUDAMiner::workLoop()':
CUDAMiner.cpp:(.text+0x1229): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x14db): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x14f9): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x1508): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1512): undefined reference to `dev::eth::Miner::s_dagLoadMode'
CUDAMiner.cpp:(.text+0x1519): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x17c4): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1802): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1c3a): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
CUDAMiner.cpp:(.text+0x1c4d): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x1c71): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x2a5f): undefined reference to `dev::eth::Miner::s_dagCreateDevice'
CUDAMiner.cpp:(.text+0x2a6c): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x2aa3): undefined reference to `dev::eth::Miner::s_dagInHostMemory'
CUDAMiner.cpp:(.text+0x33b7): undefined reference to `dev::eth::Miner::s_dagLoadIndex'
collect2: error: ld returned 1 exit status
ethminer/CMakeFiles/ethminer.dir/build.make:109: recipe for target 'ethminer/ethminer' failed
make[2]: *** [ethminer/ethminer] Error 1
CMakeFiles/Makefile2:437: recipe for target 'ethminer/CMakeFiles/ethminer.dir/all' failed
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ddobreff** [comment]
last error I think is due to incompatible cmake version.

**Comment by red-0ne** [comment]
Same error as @ykhuat's I'm building on Gentoo and cmake is `3.7.2`

**Comment by fhlfibh** [comment]
Maybe this pull request is related to my issue https://github.com/ethereum-mining/ethminer/pull/235

**Comment by red-0ne** [comment]
@fhlfibh , try playing with cmake `system-jsoncpp` flag.
@ddobreff , CMakeLists.txt wants at least version [3.3](https://github.com/ethereum-mining/ethminer/blob/master/CMakeLists.txt#L1) but travis is apparently building with version [3.2.2](https://travis-ci.org/ethereum-mining/ethminer/jobs/269511922#L75)

**Comment by red-0ne** [comment]
@ddobreff , I tried with different versions of cmake (3.5.x, 3.3.2). Same problem

**Comment by red-0ne** [comment]
@ykhuat this is the commit failing the build 109ed8e666c67015b15e47bcf5539cb87005e689

**Comment by ykhuat** [comment]
@red-0ne Tomorrow i will try it up and let all know the result. My Cmake is version 3.5.1

**Comment by smurfy** [comment]
@ykhuat: your error should be fixed in latest master see: #268 #269 
@fhlfibh: why compile without hunter? as i understand it, with hunter should be a lot easier, because it ensures all dependencies are met.

**Comment by fhlfibh** [comment]
@smurfy I already have all dep libs pulled in. With Hunter it seems Ii will just get more trouble with building Hunter itself. And at the moment I'm not sure that my last linking issue is because of _no-hunter_ build.
Anyway, later I will try to make it with Hunter, too.

**Comment by ykhuat** [comment]
@smurfy All working fine now... TQ for the help...

**Comment by fhlfibh** [comment]
@smurfy On my system it now compiles, with Hunter, OpenCL enabled and CUDA disabled.

However, it still doesn't go with OpenCL disabled and CUDA disabled, even with Hunter. It wants CUDA_TOOLKIT_ROOT_DIR (Nvidia's CUDA SDK, as far as I can understand):
```
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:642 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
```

And nevertheless, it would be great to have it built without Hunter...

**Comment by smurfy** [comment]
hmm.  OpenCL disabled and Cuda disabled?  how should that work?
Or do you mean both enabled? 
You need to install the cuda toolkit manually (at least i needed that on ubuntu)

``wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run``

Then install

``sh ./cuda_8.0.61_375.26_linux-run --override --no-opengl-lib``

**Comment by fhlfibh** [comment]
@smurfy No, I tried two variants, both with Hunter: a) OCL on and CUDA off -- it goes Ok, and b) OCL off and CUDA on -- it wants the toolkit. Though I didn't yet try the both enabled.
Will check it with CUDA toolkit manually installed.
However, it seems that I have all other deps already in place, pulled in by other packages, and Hunter only downloads them once again...

**Comment by smurfy** [comment]
I cant help you with non-hunter builds, but i did need to manually provide the CUDA Toolkit (what i linked for linux) even with Hunter builds. (Linux and Windows).

**Comment by fhlfibh** [comment]
With nvidia-cuda-toolkit manually installed it compiles for me with CUDA on / OCL off via Hunter.

**Comment by DeadManWalkingTO** [comment]
Any news here?

**Comment by RandhirRaj1123** [comment]
How to Install Json-C in Linux (Ubuntu)?
